### PR TITLE
sfm_t22 - implement flickr harvester

### PR DESCRIPTION
**Pull request by justinlittman**

### CODE REVIEW

**Comment by justinlittman** [comment]
Per @dchud, add installation instructions to README (like other GW projects).

**Comment by justinlittman** [comment]
@dchud -- the 2 problems that we encountered should be fixed.

**Comment by dchud** [comment]
Progress:  unit tests pass now.

But:  issues with three integration tests, as follows.

```python
% docker exec docker_sfmflickrharvester_1 python -m unittest discover && yo DONE
EDEBUG:harvester.state_store:Setting state for resource_type1 with key key1 to value1
DEBUG:harvester.state_store:Storing harvest state to /tmp/tmpardZyj/state.json
DEBUG:harvester.state_store:Loading state from /tmp/tmpardZyj/state.json
.DEBUG:harvester.state_store:Setting state for resource_type1 with key key1 to value1
DEBUG:harvester.state_store:Setting state for resource_type1 with key key1 to value2
DEBUG:harvester.state_store:Setting state for resource_type1 with key key1 to None
.EE
======================================================================
ERROR: tests.harvester.test_httplib_helper (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: tests.harvester.test_httplib_helper
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/local/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "/opt/sfm-flickr-harvester/tests/harvester/test_httplib_helper.py", line 1, in <module>
    import flickrapi
ImportError: No module named flickrapi


======================================================================
ERROR: tests.harvester.test_warc (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: tests.harvester.test_warc
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/local/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "/opt/sfm-flickr-harvester/tests/harvester/test_warc.py", line 5, in <module>
    import harvester.warc as sfh_warc
  File "/opt/sfm-flickr-harvester/harvester/warc.py", line 4, in <module>
    import warc as ia_warc
ImportError: No module named warc


======================================================================
ERROR: tests.test_flickr_harvester (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: tests.test_flickr_harvester
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/local/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "/opt/sfm-flickr-harvester/tests/test_flickr_harvester.py", line 3, in <module>
    import flickr_harvester
  File "/opt/sfm-flickr-harvester/flickr_harvester.py", line 2, in <module>
    import flickrapi
ImportError: No module named flickrapi


----------------------------------------------------------------------
Ran 5 tests in 0.164s

FAILED (errors=3)
```

**Comment by justinlittman** [comment]
Hmmm ... I'd suggest killing and then removing the containers and then bringing them back up.  I can either look over your shoulder on Tuesday or webex today.

**Comment by dchud** [comment]
Ah, I was executing the integration tests immediately after bringing the container(s) up, and with the daemon detaching/returning immediately I probably hadn't given it enough time to complete the installation.  After waiting a few moments, the integration tests run, taking some time, then returns this:

```python
% docker exec docker_sfmflickrharvester_1 python -m unittest discover
sssssssssssssssssssssINFO:pika.adapters.base_connection:Connecting to 172.17.0.17:5672
INFO:pika.adapters.blocking_connection:Created channel=1
EINFO:pika.adapters.blocking_connection:Channel.close(0, Normal Shutdown)
INFO:pika.channel:Channel.close(0, Normal Shutdown)
INFO:pika.adapters.blocking_connection:Closing connection (200): Normal shutdown
INFO:pika.connection:Closing connection (200): Normal shutdown
WARNING:pika.connection:Disconnected from RabbitMQ at mq:5672 (200): Normal shutdown
INFO:pika.adapters.blocking_connection:Connection closed; result=BlockingConnection__OnClosedArgs(connection=<pika.adapters.select_connection.SelectConnection object at 0x7f52d5c48850>, reason_code=200, reason_text='Normal shutdown')

======================================================================
ERROR: test_harvest (tests.test_flickr_harvester.TestFlickrHarvesterIntegration)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/sfm-flickr-harvester/tests/test_flickr_harvester.py", line 476, in test_harvest
    warc_created_msg = json.loads(warc_created_body)
  File "/usr/local/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
TypeError: expected string or buffer

----------------------------------------------------------------------
Ran 22 tests in 63.846s

FAILED (errors=1, skipped=21)
```

**Comment by justinlittman** [comment]
Hmm ... I can't replicate the problem.  I'll come look over your shoulder when you're back in the office.

**Comment by dchud** [comment]
All tests pass on clean ubuntu-14.04 with fresh install.

One note:  installing docker-compose didn't go smoothly according to recommended instructions.  It was easier to use pip to install it.  Might be worth stating explicitly.  Sending back to @justinlittman for consideration.

**Comment by dchud** [comment]
Also of note - the tests are infinitely faster on linux/docker.  Like, instantaneous.  On OSX they take much more time.  So either the OSX environment I set up is messed up, or perhaps the tests aren't executing successfully.  Or maybe they're just faster?

**Comment by justinlittman** [comment]
I suspect this explains the speed difference:  when run inside the docker environment, the (faster) integration tests are run; when run outside the docker environment, the (slower) unit tests are run.  Which environment the tests are being run in is automatically detected and the appropriate tests are run.

Yes, the unit tests should be faster but they're more numerous so they're actually slower.

**Comment by justinlittman** [comment]
https://github.com/gwu-libraries/sfm-ui/commit/85937e4b193ea4b85f5a0d003f550fca36777e8a adds a note about pip install to install docs.

**Pull request merged**
