### PR TITLE
refs sfm_57. Refactored flickr harvester to use BaseHarvester/warcprox.

### PR DESCRIPTION
**Pull request by justinlittman**

### CODE REVIEW

**Comment by kerchner** [comment]
Fix CI tests.

**Comment by justinlittman** [comment]
I believe the reason the travis tests are failing is because the master branch (on which current docker containers is based) is significantly different from the branch.  This causes the integration tests to fail.

**Comment by kerchner** [comment]
@justinlittman re: your comment above.  Are you saying we should disregard CI issue and proceed with merge?  Sounds like the only other alternative would be to create a branches in docker, and that may be overkill in this case.  Am I understanding correctly?

**Comment by justinlittman** [comment]
@kerchner You are understanding correctly.  My recommendation is to ignore the failed CI build.  (Of course, if it continues after the merge I will deal with it.)

**Pull request merged**
